-- ============================================================
-- WARDEN — Database Schema
-- Oracle Autonomous Database (ATP), Oracle 26ai
-- Schema owner: ITERIA_AI (shared with FRP, SCOUT, VALIDATE)
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = iteria_ai;

CREATE TABLE warden_tenants (
    tenant_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(200)  NOT NULL,
    env               VARCHAR2(50)   NOT NULL,
    bucket_prefix     VARCHAR2(500),
    key_verifier      VARCHAR2(128),
    key_salt          RAW(16),
    payload_salt      RAW(16),
    payload_iv        RAW(12),
    payload_ct        BLOB,
    payload_json      CLOB CHECK (payload_json IS JSON),
    prov_json         CLOB CHECK (prov_json IS JSON),
    status            VARCHAR2(20)    DEFAULT 'active',
    created_at        TIMESTAMP       DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP       DEFAULT SYSTIMESTAMP
);

CREATE TABLE warden_runs (
    run_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         NUMBER         NOT NULL REFERENCES warden_tenants(tenant_id),
    run_key           VARCHAR2(40)   NOT NULL,
    run_type          VARCHAR2(20)   NOT NULL,
    as_of_date        DATE,
    source_label      VARCHAR2(500),
    object_key        VARCHAR2(1000),
    stats_json        CLOB,
    status            VARCHAR2(20)    DEFAULT 'pending',
    created_at        TIMESTAMP       DEFAULT SYSTIMESTAMP,
    completed_at      TIMESTAMP,
    CONSTRAINT warden_runs_uq UNIQUE (tenant_id, run_key)
);

CREATE INDEX idx_warden_runs_tenant ON warden_runs(tenant_id, run_type, as_of_date);

CREATE TABLE warden_jobs (
    job_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type          VARCHAR2(30)   NOT NULL,
    status            VARCHAR2(20)   DEFAULT 'pending',
    tenant_id         NUMBER         REFERENCES warden_tenants(tenant_id),
    payload_json      CLOB,
    error_message     CLOB,
    created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    claimed_at        TIMESTAMP,
    started_at        TIMESTAMP,
    completed_at      TIMESTAMP
);

CREATE INDEX idx_warden_jobs_status ON warden_jobs(status, created_at);

CREATE TABLE warden_ledger (
    ledger_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         NUMBER         NOT NULL REFERENCES warden_tenants(tenant_id),
    entry_key         VARCHAR2(200)  NOT NULL,
    scope             VARCHAR2(20),
    decision          VARCHAR2(30)     NOT NULL,
    target_ref        VARCHAR2(100),
    unit              VARCHAR2(200),
    rule_id           VARCHAR2(20),
    rationale         CLOB,
    evidence_label    VARCHAR2(500),
    decided_by        VARCHAR2(100),
    decided_at        DATE             DEFAULT SYSDATE,
    expires_at        DATE,
    status            VARCHAR2(20)     DEFAULT 'active',
    supersedes_id     NUMBER           REFERENCES warden_ledger(ledger_id),
    created_at        TIMESTAMP        DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_warden_ledger_tenant ON warden_ledger(tenant_id, status);

CREATE TABLE warden_rules (
    rule_id           VARCHAR2(20)   NOT NULL,
    tenant_id         NUMBER         NOT NULL REFERENCES warden_tenants(tenant_id),
    name              VARCHAR2(500),
    cycle             VARCHAR2(50),
    module            VARCHAR2(100),
    tier              VARCHAR2(20),
    status            VARCHAR2(20)   DEFAULT 'available',
    cross_module      VARCHAR2(1)      DEFAULT 'N',
    eval_result       VARCHAR2(20),
    people_flagged    NUMBER         DEFAULT 0,
    config_json       CLOB,
    updated_at        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT warden_rules_pk PRIMARY KEY (tenant_id, rule_id)
);

CREATE TABLE warden_remediation (
    tenant_id         NUMBER         NOT NULL REFERENCES warden_tenants(tenant_id),
    person_ref        VARCHAR2(100)  NOT NULL,
    status            VARCHAR2(30)   DEFAULT 'Open',
    owner             VARCHAR2(100),
    due_label         VARCHAR2(50),
    updated_by        VARCHAR2(100),
    updated_at        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT warden_remediation_pk PRIMARY KEY (tenant_id, person_ref)
);

CREATE TABLE warden_staging_conflict (
    tenant_id         NUMBER         NOT NULL,
    run_id            NUMBER         NOT NULL,
    person_ref        VARCHAR2(100),
    rule_id           VARCHAR2(20),
    disposition       VARCHAR2(100),
    unit              VARCHAR2(200),
    raw_json          CLOB
);

CREATE TABLE warden_staging_model (
    tenant_id         NUMBER         NOT NULL,
    run_id            NUMBER         NOT NULL,
    entity_type       VARCHAR2(20),
    entity_key        VARCHAR2(500),
    parent_key        VARCHAR2(500),
    raw_json          CLOB
);

CREATE INDEX idx_warden_stg_conflict ON warden_staging_conflict(tenant_id, run_id);
CREATE INDEX idx_warden_staging_model ON warden_staging_model(tenant_id, run_id);

CREATE TABLE warden_audit_log (
    audit_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         NUMBER REFERENCES warden_tenants(tenant_id),
    actor             VARCHAR2(100),
    action            VARCHAR2(50)   NOT NULL,
    detail_json       CLOB CHECK (detail_json IS JSON),
    created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_warden_audit_tenant ON warden_audit_log(tenant_id, created_at);

CREATE TABLE warden_unit_exceptions (
    tenant_id         NUMBER         NOT NULL REFERENCES warden_tenants(tenant_id),
    rule_id           VARCHAR2(20)   NOT NULL,
    unit              VARCHAR2(200)  NOT NULL,
    rationale         CLOB,
    created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT warden_unit_exceptions_pk PRIMARY KEY (tenant_id, rule_id, unit)
);
